Repository OCA/connector-interfaces, pull requests merged in 2021-08, with the labels that each got.

#76 [13.0] connector_importer: refactor import type conf, purge not needed values on write
  connector_importer/__manifest__.py
  connector_importer/components/odoorecord.py
  connector_importer/migrations/13.0.1.5.0/pre-migration.py
  connector_importer/models/import_type.py
  connector_importer/models/record.py
  connector_importer/models/recordset.py
  connector_importer/readme/ROADMAP.rst
  connector_importer/tests/test_import_type.py
  connector_importer/tests/test_recordset.py
Labels: approved, bot is merging ⏳, ready to merge

#52 [IMP] connector_importer: new option 'use_job' on import type
  connector_importer/models/import_type.py
  connector_importer/models/record.py
Labels: bot is merging ⏳

#79 [13.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
Labels: help wanted, needs review

#80 [13.0] connector_importer: misc imp/fix
  connector_importer/components/importer.py
  connector_importer/components/odoorecord.py
  connector_importer/models/import_type.py
  connector_importer/models/record.py
  connector_importer/models/recordset.py
  connector_importer/models/sources/source_csv.py
  connector_importer/tests/common.py
  connector_importer/tests/fake_components.py
  connector_importer/tests/fake_models.py
  connector_importer/tests/test_backend.py
  connector_importer/tests/test_import_type.py
  connector_importer/tests/test_record_importer.py
  connector_importer/tests/test_record_importer_xmlid.py
  connector_importer/tests/test_recordset.py
  connector_importer/tests/test_source_csv.py
Labels: bot is merging ⏳
