Repository OCA/connector-interfaces, pull requests merged in 2022-11, with the labels that each got.

#93 [15.0] connector_importer: misc fix/imp
  connector_importer/__manifest__.py
  connector_importer/components/__init__.py
  connector_importer/components/dynamicmapper.py
  connector_importer/components/importer.py
  connector_importer/components/mapper.py
  connector_importer/components/odoorecord.py
  connector_importer/menuitems.xml
  connector_importer/models/import_type.py
  connector_importer/models/record.py
  connector_importer/models/recordset.py
  connector_importer/models/sources/source_csv.py
  connector_importer/tests/__init__.py
  connector_importer/tests/test_mapper.py
  connector_importer/tests/test_record_importer_basic.py
  connector_importer/tests/test_recordset.py
  connector_importer/utils/import_utils.py
  connector_importer/utils/mapper_utils.py
  connector_importer/utils/misc.py
  connector_importer/views/import_type_views.xml
  connector_importer/views/source_views.xml
Labels: approved, bot is merging ⏳

#98 [15.0] connector_importer: misc fix/imp
  connector_importer/components/dynamicmapper.py
  connector_importer/components/importer.py
  connector_importer/components/odoorecord.py
  connector_importer/models/import_type.py
  connector_importer/readme/ROADMAP.rst
  connector_importer/tests/fake_components.py
  connector_importer/tests/test_import_type.py
  connector_importer/utils/mapper_utils.py
  connector_importer/utils/misc.py
Labels: bot is merging ⏳

#96 [15.0][MIG] connector_importer_source_sftp
  connector_importer_source_sftp/README.rst
  connector_importer_source_sftp/__init__.py
  connector_importer_source_sftp/__manifest__.py
  connector_importer_source_sftp/components/__init__.py
  connector_importer_source_sftp/components/event_listeners.py
  connector_importer_source_sftp/demo/import_source_demo.xml
  connector_importer_source_sftp/demo/storage_backend_demo.xml
  connector_importer_source_sftp/i18n/connector_importer_source_sftp.pot
  connector_importer_source_sftp/models/__init__.py
  connector_importer_source_sftp/models/source_csv_sftp.py
  connector_importer_source_sftp/models/source_mixin.py
  connector_importer_source_sftp/readme/CONTRIBUTORS.rst
  connector_importer_source_sftp/readme/DESCRIPTION.rst
  connector_importer_source_sftp/security/ir.model.access.csv
  connector_importer_source_sftp/static/description/icon.png
  connector_importer_source_sftp/static/description/index.html
  connector_importer_source_sftp/tests/__init__.py
  connector_importer_source_sftp/tests/common.py
  connector_importer_source_sftp/tests/test_csv_sftp_source.py
  connector_importer_source_sftp/tests/test_event_listener.py
  connector_importer_source_sftp/views/source_csv_sftp.xml
  setup/connector_importer_source_sftp/odoo/addons/connector_importer_source_sftp
  setup/connector_importer_source_sftp/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#104 [15.0] Update pre-commit config
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: needs review

#100 [15.0] connector_importer: misc fix/imp
  connector_importer/components/dynamicmapper.py
  connector_importer/components/odoorecord.py
  connector_importer/utils/mapper_utils.py
Labels: bot is merging ⏳
